### ISSUE TITLE
CMS config & UX feeback issues

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#104]
### TODOs from 2/20/20 Meeting

- [x] Configure News to add fields for link & defaults
- [x] Add name field back to email form
- [x] Fix broken title in Timeline
- [x] why page intro not showing
- [x] configure hero form, data/index/index.en.yml
- [ ] Timeline text configure in CMS 
- [ ] ~Add map as component option~
- [ ] Images uploaded to Netlify don't have proper path https://atxcensus2020.com/img/austin-seal.png
- [ ] Add emails under images with email icon
- [x] Add LGBTQ+ community group

### Julia's suggestions

- [ ] Width of community images on mobile should be full screen instead of two per row
- [ ] Titles of Quicklinks should be underline & active hover state
- [ ] Text under Communities header: "These communities are most at risk of being undercounted. Connect with local community leaders organizing census outreach efforts."
- [ ] Organize in your neighborhood...: "**Click on the map below** to find out more..."
- [ ] Last FAQ response needs a link to the map, email need hyperlink too
- [ ] Faq citizenship: link to online
- [ ] Text too big on mobile for homepage "What is the Census?"
- [ ] Make email form collapsed by default

### Other Refactors
- [ ] Split out shared components text content from being edited on the index page.
- [ ] Separate Communities component from Map component and make Map component a dropdown option in CMS config
- [ ] If missing articles for a language, use English
- [ ] when you switch the language, stay on the same content page.
