### ISSUE TITLE
Website Pages/Content Types/Components

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#15]
**Pages:**
- [x] Landing page #18 
- [ ] Stay Connected
   - [ ] Events #23
- [ ] About/Overview page #22
  - Timeline component #26 
  - How to complete the census
- [ ] Why the Census Matters #25
  - here is where HTC map lives #21 
- [ ] FAQ page #56 

**Other pages**
- [ ] Census Materials (printable lit) #25
- [ ] "Community Portals" #14
- [ ] News #24
    - section for meetings, notes, committees

**Content Types**
- News Blog
- Media Stories 
- Videos

**Comment by tara-olson-atx** [comment]
See here for my vision on pages/content:

https://docs.google.com/document/d/1bbRejXUVKg-x1PcFh0SBMtN_22jCkfkJ8KrtTilZan0/edit?usp=sharing
