### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#18]
This is the roughest mockup ever...

<img width="264" alt="Screen Shot 2019-11-05 at 10 58 01 PM" src="https://user-images.githubusercontent.com/5697474/68269565-dbcf3f00-001f-11ea-808b-15b44b07f77f.png">

Components from top to bottom:
- [x] Menu bar #19
- [x] Call to Action/hero/carousel #20
- [x] "Community Portal" links. Each photo represents a hard to count (HTC) community #14
- [x] Timeline of census activities (once implement to be moved above social) #26
- [x] social links/embeds #10 #11
- [x] upcoming events #23
- [x] news previews and links #24

Not pictured:
- [x] Quick Links #27 (moved above social)
